#!/usr/bin/env ruby
# frozen_string_literal: true

require 'time'
require_relative 'lib/task_handler'
require_relative 'lib/console'

task_handler = TaskHandler.new

begin
  case ARGV[0]
  when 'list'
    if !ARGV[1] || Task::STATUSES.include?(ARGV[1])
      Console.print(task_handler.list(ARGV[1]))
    else
      Console.usage
    end
  when 'add'
    task_handler.add(ARGV[1..].join(' '))
  when 'update'
    task_handler.update(ARGV[1], ARGV[2..].join(' '))
  when 'delete'
    task_handler.delete(ARGV[1])
  when 'mark-in-progress'
    task_handler.mark(ARGV[1], 'in-progress')
  when 'mark-done'
    task_handler.mark(ARGV[1], 'done')
  else
    Console.usage
  end
rescue RuntimeError => e
  puts e
  exit 1
end
